name: Lint Postman API spec
on: push
jobs:
  lint-api-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Lint API spec
        run: |
          postman spec lint "e34b1678-c1b1-44dd-b912-d347a0ed0f1c" --fail-severity ERROR
